name: "apk"
on:
  push:
    branches:
      - master

  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # These versions must be strings. E.g. Otherwise `3.10` -> `3.1` 
        alpine:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    env:
      APK_KEY_RSA: "${{ secrets.APK_KEY_RSA }}"
      APK_PACKAGES_PATH: /packages/artifacts/${{matrix.alpine}}
      PACKAGER: ops@cloudposse.com
      PACKAGER_PRIVKEY: /dev/shm/ops@cloudposse.com.rsa
      PACKAGER_PUBKEY: /packages/artifacts/ops@cloudposse.com.rsa.pub

    container: cloudposse/packages-apkbuild:${{matrix.alpine}}
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: "Debug"
        run: "pwd && ls -al"
      - name: "Export"
        run: "make -C .github/ export"
      - name: "Build alpine packages"
        run: "make -C vendor/terraform apk"

