name: "apk"
on:
  push:
    branches:
      - master

  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # These versions must be strings. E.g. Otherwise `3.10` -> `3.1` 
        alpine:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: "Build and push docker image to DockerHub"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}-apkbuild
          dockerfile: apk/Dockerfile-${{matrix.alpine}}
          tags: ${{matrix.alpine}}
          registry: registry-1.docker.io
          tag_with_ref: true
          tag_with_sha: true
      - name: "Build alpine packages"
        uses: docker://cloudposse/packages-apkbuild:${{matrix.alpine}}
        with:
          args: "sh -c 'make -C /packages/vendor/terraform build'"
        env:
          APK_PACKAGES_PATH: /packages/artifacts/${{matrix.alpine}}

