name: "rakkess"
on:
  push:
    branches:
      - master
    paths:
      - apk/**
      - vendor/rakkess/**


  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - apk/**
      - vendor/rakkess/**

jobs:
  # Build for alpine linux
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # These versions must be strings. E.g. Otherwise `3.10` -> `3.1`
        alpine:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    env:
      APK_KEY_RSA: "${{ secrets.APK_KEY_RSA }}"
      APK_PACKAGES_PATH: ${{github.workspace}}/artifacts/${{matrix.alpine}}
      PACKAGER: ops@cloudposse.com
      PACKAGER_PRIVKEY: /dev/shm/ops@cloudposse.com.rsa
      PACKAGER_PUBKEY: ${{github.workspace}}/artifacts/ops@cloudposse.com.rsa.pub

    container: cloudposse/packages-apkbuild:${{matrix.alpine}}
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: "Export"
        run: "make -C .github/ export"
      - name: "Build alpine packages"
        run: "make -C vendor/${{github.workflow}} apk"
      - name: "List packages"
        run: 'find ${APK_PACKAGES_PATH} -type f -name \*.apk | xargs ls -l'
      - name: "Set output path to artifact"
        id: artifact
        run: 'echo "::set-output name=path::$(find artifacts/ -type f -name \*.apk)"'
      - name: "Determine package repo"
        id: repo
        run: |
          if [[ ${GITHUB_REF} == 'refs/heads/master' ]]; then
              echo "::set-output name=org::${{github.repository_owner}}"
          else
              echo "::set-output name=org::${{github.repository_owner}}-dev"
          fi
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: "Push artifact to package repository"
        id: push
        uses: cloudsmith-io/action@0.3.1
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'alpine'
          owner: '${{steps.repo.outputs.org}}'              # Your Cloudsmith account name or org name (namespace)
          repo: 'packages'                                  # Your Cloudsmith Repository name (slug)
          distro: 'alpine'                                  # Your Distribution  (i.e Debian, Ubuntu)
          release: 'v${{matrix.alpine}}'                    # Your Distribution Release (i.e xenial, buster)
          republish: 'true'                                 # Needed if version is not changing
          file: '${{steps.artifact.outputs.path}}'          # Package filename (including path)
