name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Slash Command Dispatch
        uses: cloudposse/actions/github/slash-command-dispatch@0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: cloudposse/packages@add-readme-build-action
          commands: rebuild-readme
          permission: none
          issue-type: both
